### ISSUE TITLE
[BUG] ElevenClock updates background color when hidden | ElevenClock causes black screen in netflix

### ISSUE THREAD

**Issue by anders-x3** [martinet101/ElevenClock#622]
## Describe the bug
When ElevenClock is on any netflix video will not render in fullscreen mode. It is only black screen. However the issue does not occur in low CPU mode.

## To Reproduce
Steps to reproduce the behaviour:
1. Open Netflix windows app
2. start any show in netflix
3. click fullscreen in netflix
4. video screen is black, the controls still show

## Expected behaviour
netflix should work

## Additional context
As i said low CPU mode removes the issue, I also tried on my second screen, same issue, unless i select "don't show clock on secondary displays". So any screen where the clock is active the netflix video doesn't show. I also tried the experimental "check only the focused window on the fullscreen check" didn't help.

##Screenshot
Here's a screenshot of my monitor setup since that's something that was asked for in the other netflix related threat
#85 

![image](https://user-images.githubusercontent.com/58751666/154760215-ee059b9e-45e2-45e2-b088-5933ffea6299.png)

**Comment by martinet101** [comment]
Could you please send your log?

**Comment by anders-x3** [comment]
[elevenclockLOG.txt](https://github.com/martinet101/ElevenClock/files/8102925/elevenclockLOG.txt)

**Comment by martinet101** [comment]
Mhmm, nothing weird appears on the log...
When you play netflix, the clock stills visible?

**Comment by anders-x3** [comment]
The clock is not visible even if the video goes black. I have right now blacklisted my main screen in elevenclock so i can watch netflix without hassle, it's not a big problem for myself i just wanted to put it on your radar.

**Comment by martinet101** [comment]
Could you try disabling the automated background color?

**Comment by anders-x3** [comment]
that fixes it.

**Comment by martinet101** [comment]
Ok, I see what is happening:

Since ElevenClock makes a small screenshot to get the background color, Netflix detects some kind of screen recording and empties the screen. Gotta fix that, because that shouldn't be ran when the clock is not visible.

**Comment by martinet101** [comment]
The issue has been fixed and will be published with the next release

**Comment by xsm1997** [comment]
I can confirm that this issue can be reproduced in 3.6.4

**Comment by martinet101** [comment]
On version 3.6.3 this did not happen, right?

**Comment by xsm1997** [comment]
> On version 3.6.3 this did not happen, right?

Even on version 3.3.0 (the first version with the Netflix fixes), I still get a black screen in Netflix UWP app.

Tested 3.3.0, 3.6.3, 3.6.4. All black screen.

**Comment by xsm1997** [comment]
Note that when I trigger fullscreen on Netflix, the video splashes several times and then get black. The splash interval is about 300-800 ms (not sure).

Maybe you still try to capture the screen several times and thus triggered some anti-record mechanism of Netflix?

**Comment by martinet101** [comment]
Oh, I see. 

What happens if you disable taskbar background color?

**Comment by xsm1997** [comment]
> Oh, I see.
> 
> What happens if you disable taskbar background color?

When I disable taskbar background color, or manually set a background color, or enable low cpu mode, the Netflix no longer goes black.

**Comment by martinet101** [comment]
Do you have your clock to show over fullscreen windows?

**Comment by xsm1997** [comment]
> Do you have your clock to show over fullscreen windows?

No, my clock never shows on fullscreen windows (e.g. games, or even Netflix).

**Comment by martinet101** [comment]
If you enable this the issue persists, right?

![image](https://user-images.githubusercontent.com/53119851/182196769-a907d6fb-3060-4069-98ad-a108dc32646b.png)

**Comment by xsm1997** [comment]
> If you enable this the issue persists, right?
> 
> ![image](https://user-images.githubusercontent.com/53119851/182196769-a907d6fb-3060-4069-98ad-a108dc32646b.png)

Yes, with that option enabled the issue persists.

**Comment by martinet101** [comment]
Allright. I assume you have mnore than one monitor. 

What happens if you open netflix and then you hide (right-click + hide clock) any other present clocks on other monitors?

**Comment by xsm1997** [comment]
> Allright. I assume you have mnore than one monitor.

Yes, I have dual monitor.

> What happens if you open netflix and then you hide (right-click + hide clock) any other present clocks on other monitors?

Netflix will detect screen recording after enter fullscreen, and if it is sure that someone is recording, the screen will be black all the time for the session. So after entering fullscreen, it is no use to hide the clock.

By the way, if I clicked 'hide clock' on the second monitor, the clock of both monitors got hidden. If I disable the clock on the second screen in the settings, the issue persists.

Also, I tried to enable click to hide the clock for 10 seconds in Settings. I opened Netflix, clicked the clock on the primary screen (the same screen as Netflix) to hide the clock, and then entered fullscreen. Netflix played normally for 10 seconds, and then went black.

**Comment by xsm1997** [comment]
> What happens if you open netflix and then you hide (right-click + hide clock) any other present clocks on other monitors?

Even if I disable my second monitor in Windows settings, the issue persists.

**Comment by martinet101** [comment]
@anders-x3, the issue got fixed for you or appeared again?

@xsm1997, can you please recreate the issue and send me your ElevenClock  log?

**Comment by martinet101** [comment]
I'm sorry, by recreating I meant opening sth in netflix, wait for the black screen to happen, open elevenclock settings -> Debbugging info -> Open log, and then sending it to me

**Comment by martinet101** [comment]
like recreating the _actual_ issue, not the support ticket

**Comment by xsm1997** [comment]
Alright. You can grab the log in my created closed issue.

**Comment by martinet101** [comment]
Ok

**Comment by xsm1997** [comment]
New finding: If I enter Youtube fullscreen mode in Chrome on my second monitor, ElevenClock will still show up in taskbar and splash (maybe changing color?) for a while, and finally hide out. This will not happen on my primary monitor.

**Comment by martinet101** [comment]
Then, let's say:

Suppose that you open a yt video, let the clock hide, pause the yt video and then, without exiting fullscreen yt, open netflix and play sth in the same screen. What happens? Does the video play?

**Comment by xsm1997** [comment]
Yes, with the clock hiding, Netflix plays normally.

**Comment by martinet101** [comment]
Ok, then this is a timing issue. Best I can say for now is that you set a custom background color for now, and i'll try to fix that, but I don't think this will be _fixable_...

**Comment by xsm1997** [comment]
Can you try to make the background detection routine running slower than the fullscreen detection routine, and schedule the background detection routine running after the fullscreen detection routine?

I think the background of taskbar should not change frequently. Maybe you can make an option called 'Netflix Optimization' to do so, or give us the choices of both detection interval?

As for now, the working solution is to: Disable windows blur effect, and manually set the background color of ElevenClock to #202020 (dark mode).

**Comment by martinet101** [comment]
> *edit: a new finding: it seems the fullscreen detection interval on non-primary screen is slower than primary screen. When watch Youtube in fullscreen on Chrome, it takes longer for ElevenClock to hide on my second screen than my primary screen. On my primary screen, there is almost no delay. But on my second screen I need to wait 2-5 seconds for ElevenClock to hide from taskbar. Maybe it can helps?

True, didn't know about this... Does netflix work on your secondary screen?

**Comment by xsm1997** [comment]
> > *edit: a new finding: it seems the fullscreen detection interval on non-primary screen is slower than primary screen. When watch Youtube in fullscreen on Chrome, it takes longer for ElevenClock to hide on my second screen than my primary screen. On my primary screen, there is almost no delay. But on my second screen I need to wait 2-5 seconds for ElevenClock to hide from taskbar. Maybe it can helps?
> 
> True, didn't know about this... Does netflix work on your secondary screen?

Nope. Not working on my secondary screen nor my primary screen.

**Comment by martinet101** [comment]
I'll release a new version with optimized fs checking to see if it works.
